name: Build
on:
  workflow_dispatch: # for testing
  push:
    branches:
      - 'develop'
jobs:
  coverage_tests_on_python:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          python -m pip install -r tests/requirements.txt
          python -m pip install -e '.[default,tf]'
      - name: Code instrumentation
        run: |
          python -m pytest -v --cov --cov-report xml:coverage.xml
          datum -h
      - name: Sending coverage results
        if: matrix.python-version == '3.7'
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml -t ${{ secrets.CODACY_PROJECT_TOKEN }}
