name: Linter
on: pull_request
jobs:
  Bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run checks
        run: |
          pip install --user -r <(grep "^bandit" ./requirements.txt)
          echo "Bandit version: "`bandit --version | head -1`
          bandit -r ./
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run checks
        run: |
          pip install --user -r <(grep "^isort" ./requirements.txt)
          isort --check --diff .
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run checks
        run: |
          pip install --user -r <(grep "^pylint" ./requirements.txt)
          echo "Pylint version: "`pylint --version | head -1`
          git ls-files -z '*.py' | xargs -0 pylint -r n
  remark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 12

      - name: Run checks
        run: |
          npm ci
          echo "remark version: "`npx remark --version`
          npx remark --frail .
  whitespace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check whitespace
        run: |
          empty_tree="$(git hash-object -t tree --stdin < /dev/null)"
          git diff --check "$empty_tree"
