name: CI
on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - '*'
jobs:
  build_and_tests_on_python:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          pip install coveralls tensorflow
          pip install -e ./
      - name: Unit testing
        run: |
          python -m unittest discover -v
          datum -h
      - name: Code instrumentation
        env:
          COVERALLS_SERVICE_NAME: github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coverage run -m unittest discover -v
          coverage run -a datum.py -h
          coveralls
